Dikarenakan kedua nilai mempunyai nilai perbandingan yang hampir sama, maka untuk menentukan Item yang mempunyai nilai yang sama, akan digunakan sistem random selection dengan peluang yang berdasarkan dari total jumlah mereka.

In [15]:
np.random.seed(42)

# =========================
# Cake dan Juice
# =========================

total_cake = df[df['Item'] == 'Cake']['Quantity'].sum()
total_juice = df[df['Item'] == 'Juice']['Quantity'].sum()

total_cake_juice = total_cake + total_juice

prob_cake = total_cake / total_cake_juice
prob_juice = total_juice / total_cake_juice

mask_3 = (df['Item'].isnull() & (df['Price Per Unit'] == 3.0))

df.loc[mask_3, 'Item'] = np.random.choice(
    ['Cake', 'Juice'],
    size=mask_3.sum(),
    p=[prob_cake, prob_juice]
)


# =========================
# Smoothie dan Sandwich
# =========================

total_smoothie = df[df['Item'] == 'Smoothie']['Quantity'].sum()
total_sandwich = df[df['Item'] == 'Sandwich']['Quantity'].sum()

total_smoothie_sandwich = total_smoothie + total_sandwich

prob_smoothie = total_smoothie / total_smoothie_sandwich
prob_sandwich = total_sandwich / total_smoothie_sandwich

mask_4 = (df['Item'].isnull() & (df['Price Per Unit'] == 4.0))

df.loc[mask_4, 'Item'] = np.random.choice(
    ['Smoothie', 'Sandwich'],
    size=mask_4.sum(),
    p=[prob_smoothie, prob_sandwich]
)

In [16]:
# Sistem Diupdate kembali untuk melakukan pengecekan
total_juice = df[df['Item'] == 'Juice']['Quantity'].sum()
total_cake = df[df['Item'] == 'Cake']['Quantity'].sum()

total_smoothie = df[df['Item'] == 'Smoothie']['Quantity'].sum()
total_sandwich = df[df['Item'] == 'Sandwich']['Quantity'].sum()

print("Total Juice:", total_juice)
print("Total Cake:", total_cake)
print("Total Smoothie:", total_smoothie)
print("Total Sandwich:", total_sandwich)

Total Juice: 3892
Total Cake: 3838
Total Smoothie: 3645
Total Sandwich: 3824

Bagian yang memiliki total spent 25.0 sudah mempunyai nilai pasti pada kolom quantity dan price per unit, yaitu 5 dan 5.0, dikarenakan kedua nilai tersebut adalah nilai tertinggi dari kedua kolom tersebut. Begitu juga dengan total spent 9.0 dan 16.0 dikarenakan tidak ada perkalian yang bisa mencapai angka total spent tersebut.

In [17]:
# ======================================================
# Mengisi Item, Quantity, dan Price Per Unit yang kosong
# berdasarkan Total Spent tertentu: 25.0, 9.0, dan 16.0
# ======================================================

np.random.seed(42)

base_mask = (
    df['Item'].isna() &
    df['Quantity'].isna() &
    df['Price Per Unit'].isna() &
    df['Total Spent'].notna()
)

# ======================================================
# Total Spent = 25.0
# Quantity = 5, Price Per Unit = 5.0, Item = Salad
# ======================================================

mask_25 = base_mask & (df['Total Spent'] == 25.0)

df.loc[mask_25, 'Quantity'] = 5
df.loc[mask_25, 'Price Per Unit'] = 5.0
df.loc[mask_25, 'Item'] = 'Salad'


# ======================================================
# Total Spent = 9.0
# Quantity = 3, Price Per Unit = 3.0
# Item = Cake atau Juice berdasarkan rasio total Quantity
# ======================================================

mask_9 = base_mask & (df['Total Spent'] == 9.0)

df.loc[mask_9, 'Quantity'] = 3
df.loc[mask_9, 'Price Per Unit'] = 3.0

total_cake = df[df['Item'] == 'Cake']['Quantity'].sum()
total_juice = df[df['Item'] == 'Juice']['Quantity'].sum()

total_cake_juice = total_cake + total_juice

prob_cake = total_cake / total_cake_juice
prob_juice = total_juice / total_cake_juice

df.loc[mask_9, 'Item'] = np.random.choice(
    ['Cake', 'Juice'],
    size=mask_9.sum(),
    p=[prob_cake, prob_juice]
)


# ======================================================
# Total Spent = 16.0
# Quantity = 4, Price Per Unit = 4.0
# Item = Smoothie atau Sandwich berdasarkan rasio total Quantity
# ======================================================

mask_16 = base_mask & (df['Total Spent'] == 16.0)

df.loc[mask_16, 'Quantity'] = 4
df.loc[mask_16, 'Price Per Unit'] = 4.0

total_smoothie = df[df['Item'] == 'Smoothie']['Quantity'].sum()
total_sandwich = df[df['Item'] == 'Sandwich']['Quantity'].sum()

total_smoothie_sandwich = total_smoothie + total_sandwich

prob_smoothie = total_smoothie / total_smoothie_sandwich
prob_sandwich = total_sandwich / total_smoothie_sandwich

df.loc[mask_16, 'Item'] = np.random.choice(
    ['Smoothie', 'Sandwich'],
    size=mask_16.sum(),
    p=[prob_smoothie, prob_sandwich]
)


# ======================================================
# Cek jumlah data yang berhasil diisi
# ======================================================

print("Jumlah data Total Spent 25.0 yang diisi:", mask_25.sum())
print("Jumlah data Total Spent 9.0 yang diisi:", mask_9.sum())
print("Jumlah data Total Spent 16.0 yang diisi:", mask_16.sum())

Jumlah data Total Spent 25.0 yang diisi: 1
Jumlah data Total Spent 9.0 yang diisi: 1
Jumlah data Total Spent 16.0 yang diisi: 0

Setelah diisi, data dari keempat kolom tersebut (Item, Quantity, Price Per Unit, dan Total Spent) akan dicek kembali mana bagian yang masih kosong

In [18]:
# Menampilkan Quantity yang null
df[(df['Quantity'].isnull())]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,<NA>,5.0,NaN,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,<NA>,3.0,NaN,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,<NA>,3.0,NaN,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,<NA>,4.0,NaN,NaN,Takeaway,2023-05-14
2796,TXN_9188692,Cake,<NA>,3.0,NaN,Credit Card,NaN,2023-12-01
3203,TXN_4565754,Smoothie,<NA>,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,<NA>,2.0,NaN,NaN,NaN,2023-04-07
3401,TXN_3251829,Tea,<NA>,1.5,NaN,Digital Wallet,In-store,2023-07-25
4257,TXN_6470865,Coffee,<NA>,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,<NA>,1.0,NaN,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,<NA>,2.0,NaN,Cash,NaN,2023-12-25
7297,TXN_9944500,Smoothie,<NA>,4.0,NaN,Cash,In-store,2023-01-03
8021,TXN_2428781,Salad,<NA>,5.0,NaN,NaN,In-store,2023-05-09
8443,TXN_2023651,Sandwich,<NA>,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,<NA>,2.0,NaN,NaN,<NA>,2023-06-03
8479,TXN_1547245,Sandwich,<NA>,4.0,NaN,NaN,Takeaway,2023-09-11
8574,TXN_2546684,Juice,<NA>,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,<NA>,1.0,NaN,Credit Card,In-store,2023-08-04
9590,TXN_9924732,Sandwich,<NA>,4.0,NaN,Credit Card,In-store,2023-01-18
9819,TXN_1208561,NaN,<NA>,NaN,20.0,Credit Card,NaN,2023-08-19
9869,TXN_1975184,Coffee,<NA>,2.0,NaN,Digital Wallet,NaN,2023-01-15

In [19]:
# Menampilkan Total Spent yang null
df[(df['Total Spent'].isnull())]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,<NA>,5.0,NaN,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,<NA>,3.0,NaN,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,<NA>,3.0,NaN,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,<NA>,4.0,NaN,NaN,Takeaway,2023-05-14
1761,TXN_3611851,NaN,4,NaN,NaN,Credit Card,NaN,2023-02-09
2289,TXN_7524977,<NA>,4,NaN,NaN,<NA>,NaN,2023-12-09
2796,TXN_9188692,Cake,<NA>,3.0,NaN,Credit Card,NaN,2023-12-01
3203,TXN_4565754,Smoothie,<NA>,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,<NA>,2.0,NaN,NaN,NaN,2023-04-07
3401,TXN_3251829,Tea,<NA>,1.5,NaN,Digital Wallet,In-store,2023-07-25
4152,TXN_9646000,<NA>,2,NaN,NaN,NaN,In-store,2023-12-14
4257,TXN_6470865,Coffee,<NA>,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,<NA>,1.0,NaN,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,<NA>,2.0,NaN,Cash,NaN,2023-12-25
7297,TXN_9944500,Smoothie,<NA>,4.0,NaN,Cash,In-store,2023-01-03
8021,TXN_2428781,Salad,<NA>,5.0,NaN,NaN,In-store,2023-05-09
8443,TXN_2023651,Sandwich,<NA>,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,<NA>,2.0,NaN,NaN,<NA>,2023-06-03
8479,TXN_1547245,Sandwich,<NA>,4.0,NaN,NaN,Takeaway,2023-09-11
8574,TXN_2546684,Juice,<NA>,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,<NA>,1.0,NaN,Credit Card,In-store,2023-08-04
9590,TXN_9924732,Sandwich,<NA>,4.0,NaN,Credit Card,In-store,2023-01-18
9869,TXN_1975184,Coffee,<NA>,2.0,NaN,Digital Wallet,NaN,2023-01-15

Dari sini kita bisa mengetahui bahwa nilai kosong pada Quantity dan Total Spent sama.

Selanjutnya nilai kosong pada Item dan Price per Unit.

In [20]:
# Menampilkan Price Per Unit yang null
df[(df['Price Per Unit'].isnull())]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1761,TXN_3611851,NaN,4,NaN,NaN,Credit Card,NaN,2023-02-09
2289,TXN_7524977,<NA>,4,NaN,NaN,<NA>,NaN,2023-12-09
4152,TXN_9646000,<NA>,2,NaN,NaN,NaN,In-store,2023-12-14
9819,TXN_1208561,NaN,<NA>,NaN,20.0,Credit Card,NaN,2023-08-19

In [21]:
# Menampilkan Item null
df[df['Item'].isnull()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1761,TXN_3611851,NaN,4,NaN,NaN,Credit Card,NaN,2023-02-09
2289,TXN_7524977,<NA>,4,NaN,NaN,<NA>,NaN,2023-12-09
4152,TXN_9646000,<NA>,2,NaN,NaN,NaN,In-store,2023-12-14
9819,TXN_1208561,NaN,<NA>,NaN,20.0,Credit Card,NaN,2023-08-19

In [22]:
# Total Item
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<NA>,<NA>,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,<NA>,2023-08-30
9996,TXN_9659401,Cookie,3,1.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

Lalu dilanjutkan untuk cleaning bagian Payment Method dan Location

In [23]:
# Menampilkan jumlah dari setiap unique payment method
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

In [24]:
df['Payment Method'].isnull().sum()

np.int64(3178)

Dengan cara yang sama, untuk data yang kosong di kolom Payment Method, akan digunakan random berdasarkan jumlah total dari setiap bagian pada kolom Payment Method.

In [25]:
# data yang kosong di kolom Payment Method akan diisi menggunakan random selection
# berdasarkan proporsi jumlah masing-masing Payment Method yang sudah ada

np.random.seed(42)

# Menentukan baris yang Payment Method-nya kosong
mask_payment = df['Payment Method'].isnull()

# Menghitung jumlah masing-masing metode pembayaran yang sudah ada
payment_counts = df['Payment Method'].value_counts()

print("Jumlah masing-masing Payment Method:")
print(payment_counts)

# Mengubah jumlah menjadi probabilitas
payment_probs = payment_counts / payment_counts.sum()

print("\nProbabilitas masing-masing Payment Method:")
print(payment_probs)

# Mengisi missing value berdasarkan probabilitas tersebut
df.loc[mask_payment, 'Payment Method'] = np.random.choice(
    payment_probs.index,
    size=mask_payment.sum(),
    p=payment_probs.values
)

Jumlah masing-masing Payment Method:
Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

Probabilitas masing-masing Payment Method:
Payment Method
Digital Wallet    0.335825
Credit Card       0.333187
Cash              0.330988
Name: count, dtype: float64

In [26]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    3365
Credit Card       3329
Cash              3306
Name: count, dtype: int64

Dan juga kolom Location

In [27]:
df['Location'].value_counts()

Location
Takeaway    3022
In-store    3017
Name: count, dtype: int64